name: Docker Build and Push

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag argocd-grafana-annotator:$GITHUB_SHA
    - name: Push the image
      run: docker push andrew-waters/argocd-grafana-annotator:$GITHUB_SHA
